atividadefinecap/Finecap/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace='index')),
    path('accounts/', include('allauth.urls')),
    path("", include("reservas.urls", namespace="reservas")),
    path("", include("stands.urls", namespace="stands"))

]

atividadefinecap/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path('', IndexHomeView.as_view(), name='index'),
]

atividadefinecap/reservas/urls.py
from django.contrib import admin
from django.urls import path
from reservas.views import ReservaCreateView, ReservaDeleteView, ReservaDetailView, ReservasListView, ReservaUpdateView

app_name = "reservas"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reserva/", ReservaCreateView.as_view(), name="reserva"),
    path('lista_reserva/', ReservasListView.as_view(), name='lista_reservas'),
    path('remover_reserva/<int:pk>/', ReservaDeleteView.as_view(), name="remover_reserva"),
    path('reserva_detalhe/<int:pk>/', ReservaDetailView.as_view(), name='reserva_detalhe'),
    path('update/<int:pk>/', ReservaUpdateView.as_view(), name="editar"),
    ]

atividadefinecap/stands/urls.py
from django.contrib import admin
from django.urls import path
from stands.views import StandCreateView, StandDeleteView, StandListView, StandUpdateView, StandDetailView

app_name = "stands"

urlpatterns = [
    path('lista_stands/', StandListView.as_view(), name='lista_stands'),
    path('reserva_stand/', StandCreateView.as_view(), name="reserva_stand"),
    path('remover_stand/<int:pk>/', StandDeleteView.as_view(), name="remover_stand"),
    path('update_stand/<int:pk>/', StandUpdateView.as_view(), name="editar_stand"),
    path('stand_detalhe/<int:pk>/', StandDetailView.as_view(), name='stand_detalhe'),
]

atividadefinecap/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="css/contato.css">
    <title>RESERVAS FINECAP 2023</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

  <style>

body {
    overflow-x: hidden;
}

  </style>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'core:index' %}">FINECAP 2023</a>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'reservas:lista_reservas' %}">Reservas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stands:lista_stands' %}">Stands</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Usuário
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Sair</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'account_signup' %}">Cadastrar</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    </nav>
</header>


    {% block main %}
    {% endblock %}


</main> 
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <script>
  $(document).ready(function(){
  $('.money').mask('0000,00', {reverse: true})
  })
  </script>
  
{% endblock javascript %}
</body>
</html>