atividadefinecap/Finecap/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace='index')),
    path('accounts/', include('allauth.urls')),
    path("", include("reservas.urls", namespace="reservas")),
    path("", include("stands.urls", namespace="stands"))

]

atividadefinecap/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path('', IndexHomeView.as_view(), name='index'),
]

atividadefinecap/reservas/urls.py
from django.contrib import admin
from django.urls import path
from reservas.views import ReservaCreateView, ReservaDeleteView, ReservaDetailView, ReservasListView, ReservaUpdateView

app_name = "reservas"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("reserva/", ReservaCreateView.as_view(), name="reserva"),
    path('lista_reserva/', ReservasListView.as_view(), name='lista_reservas'),
    path('remover_reserva/<int:pk>/', ReservaDeleteView.as_view(), name="remover_reserva"),
    path('reserva_detalhe/<int:pk>/', ReservaDetailView.as_view(), name='reserva_detalhe'),
    path('update/<int:pk>/', ReservaUpdateView.as_view(), name="editar"),
    ]

atividadefinecap/reservas/models.py
from django.db import models
from stands.models import Stand
# Create your models here.


class Reserva(models.Model):
    cnpj = models.CharField(max_length=11)
    nome_empresa = models.CharField(max_length=150)
    categoria_empresa = models.CharField(max_length=150)
    quitado = models.BooleanField(default=False)
    stand = models.ForeignKey(Stand, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome_empresa

atividadefinecap/reservas/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reserva

class ReservaForm(ModelForm):

    class Meta:
        model = Reserva
        fields = '__all__'
        widgets = {
            'cnpj' : forms.TextInput(attrs={'class': 'form-control' }),
            'nome_empresa' : forms.TextInput(attrs={'class': 'form-control' }),
            'categoria_empresa' : forms.TextInput(attrs={'class': 'form-control' }),
            'stand': forms.Select(attrs={'class': 'form-control' }),
        }

atividadefinecap/reservas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Reserva
from .forms import ReservaForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from users.permissions import GerentePermission

class ReservaCreateView(LoginRequiredMixin, generic.CreateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("reservas:lista_reservas")
    template_name = "reserva.html"

    def form_valid(self, form):
        messages.success(self.request, "Sua reserva foi cadastrada")
        return super().form_valid(form)


class ReservasListView(LoginRequiredMixin, generic.ListView):
    model = Reserva
    template_name = "lista_reservas.html"
    paginate_by = 2

class ReservaDeleteView(GerentePermission, LoginRequiredMixin, generic.DeleteView):
    model = Reserva
    success_url = reverse_lazy("reservas:lista_reservas")

    def form_valid(self, form):
        messages.error(self.request, "Sua reserva foi cancelada")
        return super().form_valid(form)
  
class ReservaUpdateView(GerentePermission, LoginRequiredMixin, generic.UpdateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("reservas:lista_reservas")
    template_name = "reserva.html"

    def form_valid(self, form):
        messages.success(self.request, "Sua reserva foi atualizada")
        return super().form_valid(form)

class ReservaDetailView(LoginRequiredMixin, generic.DetailView):
    model = Reserva
    template_name = "reserva_detalhe.html"  

atividadefinecap/reservas/templates/lista_reservas.html
{%  extends 'base.html' %}

{% block main %}
<br>
<br>

<style>
    main {
        width: 70%;
        margin: auto;
    }
</style>
<main>
<div class="text-center m-3">
    <h3 class="mt-3"> Lista das reservas</h3>

    <a href="{% url 'reservas:reserva' %}" class="btn btn-success mb-3">Novo Cadastro</a>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}

        {% if messages.warning %}
        <div class="alert alert-danger{{ message.tags }}">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endif %}

        {% endfor %}
    </div>
    {% endif %}

    <table class="table table-bordered mx-auto">
        <thead>
            <tr>
                <th>Empresa</th>
                <th>Stand</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            {% for object in object_list %}
            <tr>
                <td>{{ object.nome_empresa }}</td>
                <td>{{ object.stand }}</td>
                <td style="display: flex; justify-content: space-evenly;">
                    <div class="btn-group btn-group-toggle" data-toggle="buttons"></div>
                    <a href="{% url 'reservas:editar' object.id %}" class="btn btn-info btn-sm">Editar</a>
                    <a href="{% url 'reservas:reserva_detalhe' object.id %}" class="btn btn-primary btn-sm">Detalhar</a>
                    <a href="{% url 'reservas:remover_reserva' object.id %}" class="btn btn-danger btn-sm">Remover</a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>
</tbody>
</table>
</main>

  <div class="container">
    <div class="row">
        {% comment %}
            In this block we will display every single item in a 4 columns grid
        {% endcomment %}
        {% for item in items %}
            <div class="col-lg-3">
                {{ item.id }}). {{ item.name }}
            </div>
        {% endfor %}
    </div>
</div>

{% comment %}
    Render a Bootstrap 5 based pagination element with Django default's pagination
{% endcomment %}
<div class="row">
    <div class="col-lg-12">
        {% if page_obj.has_other_pages %}
            <nav>
                <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_number in page_obj.paginator.page_range %}
                        {% comment %}
                            This conditional allows us to display up to 3 pages before and after the current page
                            If you decide to remove this conditional, all the pages will be displayed

                            You can change the 3 to any number you want e.g
                            To display only 5 pagination items, change the 3 to 2 (2 before and 2 after the current page)
                        {% endcomment %}
                        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                            {% if page_obj.number == page_number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="?page={{ page_number }}">
                                        {{ page_number }}
                                        <span class="visually-hidden"></span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
</div>

  
{%  endblock %}

atividadefinecap/reservas/templates/reserva.html
{%  extends 'base.html' %}

{% block main %}
<br>

    <main>
        <section class="sct-form">
            
            <div class="form">
                <div class="main-content pl-sm-3 mt-4 d-flex justify-content-center align-items-center">
                <div class="col-md-6 col-lg-6 col-xl-6 col-12">
                <h1 class="mt-3">Faça sua reserva</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="nome_empresa" class="form-label">Nome da empresa</label>
                        {{ form.nome_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="empresa_categoria'" class="form-label">Categoria da empresa</label>
                        {{ form.categoria_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="CNPJ" class="form-label">CNPJ</label>
                        {{ form.cnpj }}
                    </div>
                    <div class="mb-3">
                        <label for="Stand" class="form-label">Stand</label>
                        {{ form.stand }}
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>    

            </div>
        </div>
    </div>
            
        </section>
        
    </main>

    {% endblock %}
    

atividadefinecap/reservas/templates/reserva_detalhe.html
{% extends 'base.html' %}
{% block main %}

<div class="container-fluid mt-3">
        <div class="col-lg-6">
            <h3>Detalhes da reserva</h3>
            <br>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Empresa</th>
                        <th>CNPJ</th>
                        <th>Categoria</th>
                        <th>Stand</th>
                        <th>Quitação</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ reserva.nome_empresa }}</td>
                        <td>{{ reserva.cnpj }}</td>
                        <td>{{ reserva.categoria_empresa }}</td>
                        <td>{{ reserva.stand }}</td>
                        {% if reserva.quitado %}
                        <td>Quitado</td>
                        {% else %}
                        <td>Não quitado</td>
                        {% endif %}

                    </tr>
                </tbody>
        </div>
    </div>

    {%endblock%}