atividadefinecap/Finecap/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace='index')),
    path('accounts/', include('allauth.urls')),
    path("", include("reservas.urls", namespace="reservas")),
    path("", include("stands.urls", namespace="stands"))

]

atividadefinecap/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *

app_name = "core"

urlpatterns = [
    path('', IndexHomeView.as_view(), name='index'),
]

atividadefinecap/stands/urls.py
from django.contrib import admin
from django.urls import path
from stands.views import StandCreateView, StandDeleteView, StandListView, StandUpdateView, StandDetailView

app_name = "stands"

urlpatterns = [
    path('lista_stands/', StandListView.as_view(), name='lista_stands'),
    path('reserva_stand/', StandCreateView.as_view(), name="reserva_stand"),
    path('remover_stand/<int:pk>/', StandDeleteView.as_view(), name="remover_stand"),
    path('update_stand/<int:pk>/', StandUpdateView.as_view(), name="editar_stand"),
    path('stand_detalhe/<int:pk>/', StandDetailView.as_view(), name='stand_detalhe'),
]

atividadefinecap/stands/models.py
from django.db import models

# Create your models here.
class Stand(models.Model):
    localizacao = models.CharField(max_length=150)
    valor = models.DecimalField(
    verbose_name= "Valor",
    decimal_places=2,
    max_digits=6
)

    def __str__(self):
        return self.localizacao

atividadefinecap/stands/forms.py
from django.forms import ModelForm
from django import forms
from .models import Stand
from decimal import Decimal

class StandForm(ModelForm):

    class Meta:
        model = Stand
        fields = '__all__'
         
    localizacao = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'}))
    valor = forms.DecimalField(widget=forms.TextInput(attrs={
        'class': 'money form-control',
    }), localize=True)


    def clean_valor(self):
        valor = self.cleaned_data["valor"]
        if isinstance(valor, str):
            try:
                valor = Decimal(valor.replace(",", ""))
            except ValueError:
                raise forms.ValidationError("Informe um número válido para o valor.")
        return valor

atividadefinecap/stands/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages import views
from .forms import StandForm
from .models import Stand
from django.contrib.auth.mixins import LoginRequiredMixin
from users.permissions import GerentePermission

# Create your views here.

class StandCreateView(GerentePermission, LoginRequiredMixin, generic.CreateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:lista_stands")
    template_name = "reserva_stand.html"

    def form_valid(self, form):
        messages.success(self.request, "Seu stand foi cadastrado")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        return self.render_to_response(self.get_context_data(form=form))

class StandListView(LoginRequiredMixin, generic.ListView):
    model = Stand
    template_name = "lista_stands.html"
    paginate_by = 2

class StandUpdateView(GerentePermission, LoginRequiredMixin, generic.UpdateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:lista_stands")
    template_name = "reserva_stand.html"

    def form_valid(self, form):
        messages.success(self.request, "Seu stand foi atualizado")
        return super().form_valid(form)

class StandDeleteView(GerentePermission, LoginRequiredMixin, generic.DeleteView):
    model = Stand
    success_url = reverse_lazy("stands:lista_stands")
    
    def form_valid(self, form):
        messages.error(self.request, "Seu stand foi removido")
        return super().form_valid(form)

class StandDetailView(LoginRequiredMixin, generic.DetailView):
    model = Stand
    template_name = "stand_detalhe.html" 

atividadefinecap/stands/templates/lista_stands.html
{% extends 'base.html' %}

{% block main %}
<br>
<br>

<style>
    main {
        width: 70%;
        margin: auto;
    }
</style>

<main>
<div class="text-center m-3">
<h3 class="mt-3"> Lista dos stands</h3>

<a href="{% url 'stands:reserva_stand' %}" class="btn btn-success mb-3">Novo Cadastro</a>

{% if messages %}
<div class="messages">
  {% for message in messages %}
  
  {% if messages.warning %}
  <div class="alert alert-danger{{ message.tags }}">
    {{ message }}
  </div>
  {% else %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endif %}

  {% endfor %}
</div>
{% endif %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Localização</th>
        <th>Valor</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>{{ object.localizacao }}</td>
        <td>R$ {{ object.valor }}</td>
        <td style="display: flex; justify-content: space-evenly;">
          <div class="btn-group btn-group-toggle" data-toggle="buttons"></div>
          <a href="{% url 'stands:editar_stand' object.id %}" class="btn btn-info btn-sm">Editar</a>
          <a href="{% url 'stands:stand_detalhe' object.id %}" class="btn btn-primary btn-sm">Detalhar</a>
          <a href="{% url 'stands:remover_stand' object.id %}" class="btn btn-danger btn-sm">Remover</a>
          </div>
        </td>
  
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

  <div class="container">
    <div class="row">
        {% comment %}
            In this block we will display every single item in a 4 columns grid
        {% endcomment %}
        {% for item in items %}
            <div class="col-lg-3">
                {{ item.id }}). {{ item.name }}
            </div>
        {% endfor %}
    </div>
</div>

{% comment %}
    Render a Bootstrap 5 based pagination element with Django default's pagination
{% endcomment %}
<div class="row">
    <div class="col-lg-12">
        {% if page_obj.has_other_pages %}
            <nav>
                <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for page_number in page_obj.paginator.page_range %}
                        {% comment %}
                            This conditional allows us to display up to 3 pages before and after the current page
                            If you decide to remove this conditional, all the pages will be displayed

                            You can change the 3 to any number you want e.g
                            To display only 5 pagination items, change the 3 to 2 (2 before and 2 after the current page)
                        {% endcomment %}
                        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                            {% if page_obj.number == page_number %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="?page={{ page_number }}">
                                        {{ page_number }}
                                        <span class="visually-hidden"></span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
</div>

{% endblock %}

atividadefinecap/stands/templates/reserva_stand.html
{%  extends 'base.html' %}

{% block main %}
<br>

<main>
    <section class="sct-form">
        <div class="form">
            <div class="main-content pl-sm-3 mt-4 d-flex justify-content-center align-items-center">
            <div class="col-md-6 col-lg-6 col-xl-6 col-12">
            <h1 class="mt-3">Formulário do stand</h1>
       
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nome" class="form-label">Localização</label>
            {{ form.localizacao }}
        </div>

        <div class="mb-3">
            <label for="nome" class="form-label">Valor</label>
            {{ form.valor }}
        </div>
        
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form> 
</div>
</div>
    
</section>
          
</main>
    
{% endblock %}

atividadefinecap/stands/templates/stand_detalhe.html
{% extends 'base.html' %}
{% block main %}
<div class="container-fluid mt-3">
        <div class="col-lg-6">
            <h3>Detalhes do stand</h3>
            <br>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Localização</th>
                        <th>Valor</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ stand.localizacao }}</td>
                        <td>{{ stand.valor }}</td>
                        
                    </tr>
                </tbody>
        </div>
    </div>
    {%endblock%}